#include "board.h"

namespace ConnectFour
{
    /// @brief Sequence of random numbers for each board slot and each player for generating Zobrist hash.
    ///
    /// Board::width*Board::height*2 numbers are required.
    /// Generated by random.org.
    static const Board::Hash zobristNumbers[] = {
        0xccf014f5fdcaeb95, 0x45618bcf8b8db04a, 0xb6e45b046215a50a, 0x899e35d5679ad695,
        0xbc4e9afb4d3bdbbd, 0x563b69d7db280e12, 0x20bf0f36afef951e, 0x6e44c59b3eadc023,
        0x8e40a599255ec0bd, 0xf1134a004f4cc51e, 0x0675becf6004aab3, 0x08b938e7091ae680,
        0x230405812bc87201, 0x4261bd356c960950, 0x41c5e300255ee3b5, 0x4d659bee7cb9dfa3,
        0xfddeb04953cf88f8, 0xb20f9cf52e1c531d, 0x765cf79f5c2f06e7, 0xabd6b3b2c6ed13d0,
        0x8632e2ab27060b13, 0x4bb623ea820411b7, 0x07fbdfdeb439ecda, 0x55426c23c7d67cfb,
        0xd3c00ed5f0fbbce2, 0x7123716b76d136d2, 0x20bbab3e725cc679, 0xbfb42d4f478050ca,
        0x3e1e9d9a005ee23c, 0x6fd6b68452a5cd9b, 0x7d1fe0f59e7caa83, 0x2f8165d334645b95,
        0x37d5cf355bf6fd6d, 0x659f918ffb320ee0, 0xeec58bc8de71ace3, 0x59a9800c4b916092,
        0x07ebd0f0157ef359, 0x6b6af10e0dc89196, 0x1df9757e84cbf670, 0xbf6c6173158f8566,
        0xaf3021a5f141308d, 0xb418d8e5b3a5bda6, 0x0d97aa5f70066d03, 0xc4337730a9249580,
        0x3ac5a8838095c744, 0xb7d31d56569cf8f1, 0x8aa44221d9be9723, 0x40a230e7af57468a,
        0x152385074d10e7e4, 0x55e326219e046670, 0x96db385332818555, 0xc745aa18d926bdfc,
        0xb94421448cf8c925, 0xfafc7504f0d0b3b2, 0x68fd2e8ab6d4fb18, 0xfa820a9c13c2249e,
        0xac59cd884fee759b, 0x472839686804a1f6, 0x1abc65dc1bee26a7, 0x7903647f07e01497,
        0xa3237d4e637b073c, 0x0338c3557cff7a73, 0xe8844b04f1e74512, 0x30de914e13c61d51,
        0xba5a37a8b140b996, 0x3bd128b9db75b5f3, 0x41c8bc5a74459d1d, 0x716bb8b59a8cd4f5,
        0x0ab9310da939d8a5, 0x4eb6388677b60d6e, 0xdec8053e2ba9ed5b, 0x59544b62fa232882,
        0x99136aae79a94a92, 0xd0107b764ca095bf, 0x989e016a6f147d2e, 0xffd3e03a7385a402,
        0x2e511318a18fbaab, 0x86070d605a06077d, 0x1a3387ac75c45e3c, 0xc3226ef970fb4271,
        0xa4802ad3a6012300, 0x6aff73ba84a4e6f5, 0x22441f667e6cdfaf, 0xa7e70c59d0046a24
    };
}